Add #include <cmath> in deMath.h when being compiled by C++ compiler
In below two files:

external/openglcts/modules/common/glcFramebufferBlitTests.cpp
external/openglcts/modules/common/glcTextureLodBiasTests.cpp

The math header included is deMath.h, which includes math.h.
However, the code is calling fabs and floor under std:: namespace,
which requires including <cmath> header. This results in some
compiler failed to compile these two files:

error: no member named 'floor' in namespace 'std'
error: no member named 'fabs' in namespace 'std'

Add #include <cmath> in deMath.h, when deMath.h is being compiled
by a C++ compiler.

Affected tests: None

VK-GL-CTS issue: 5177

Change-Id: Ib14444df57a5b2361bf845decf9e40f55695600d